version: "3"
services:
  api-plazoleta:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${APP_PORT}:3000"
#    command: nest start
#    restart: always
#    volumes:
#      - ./:/usr/src/app
#      - ./:/usr/src/app/node_modules

